baseURL = 'https://rusinikita.github.io/changes/'
languageCode = 'en-us'
title = 'rusinikita/changes'

[module]

[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[params]

[params.docs]
title = "Changes"
descriptions = true
backToTop = true
darkMode = true
sidebarIcons = true
titleIcon = true

[params.footer]
copyright = "© :YEAR: Nikita Rusin. Built with ❤️ and [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
version = true

[params.social]
github = "rusinikita/changes"

