baseURL = 'https://rusinikita.github.io/changes/'
languageCode = 'en-us'
title = 'Git Changes validation'

[module]

[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[params]

description = "Pull request validation tool written in Go. Spend less time on agreements validation."
keywords = "Git,PR,Pull Request,Team agreements,Validation,Automation"
version = "v1"

[params.docs]
title = "Changes"
descriptions = true
backToTop = true
darkMode = true
sidebarIcons = true
titleIcon = true
prism = true

[params.footer]
copyright = "© :YEAR: Nikita Rusin. Built with ❤️ and [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
version = true

[params.social]
github = "rusinikita/changes"

[params.author]
name = "Nikita Rusin"
website = "https://nikitarusin.com"

