name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          go-version-file: go.mod
          cache: false

      - name: git-changes_check
        run: go run cmd/custom/main.go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"

      - name: Run tests with coverage report output
        run: go test ./... -coverprofile=coverage.out

      - uses: k1LoW/octocov-action@v0