name: project checks
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          only-new-issues: true
          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"

      - name: vale
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          fail_on_error: true
          files: docs/content/docs
          filter_mode: added

  git-check:
    name: git-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # skip merge commit
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: rusinikita/changes-action@v1
        with:
          pr-message: true
