name: project checks
on:
  pull_request:
    paths:
      - '**.go'

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test ./... -coverprofile=coverage.out

      - name: octocov-coverage-gateway
        uses: k1LoW/octocov-action@v0

  mutation-tests:
    name: mutation-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: gramlins-mutation-testing
        uses: go-gremlins/gremlins-action@v1
        with:
          version: 'v0.5.0'
          args: ""
          workdir: .