name: project checks
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: test-git-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # skip merge commit
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: rusinikita/changes-action@v0.3